// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertDescription
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertDescription.1d3bc79a-7f6a-4d81-bedb-5d8a26b0a62a";
        public const string Name = "Insert Description";
        public const string Description = @"The easiest way to insert a description into the editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Enes Gelmez";
        public const string Tags = "";
    }
}
